Repository webauthn4j/webauthn4j, pull requests merged in 2019-10, with the labels that each got.

#144 Remove unnessesary setters
  webauthn4j-core/src/main/java/com/webauthn4j/authenticator/Authenticator.java
Labels: breaking change

#147 Add INTERNAL constant to AuthenticatorTransport
  webauthn4j-core/src/main/java/com/webauthn4j/data/AuthenticatorTransport.java
  webauthn4j-core/src/test/java/com/webauthn4j/data/AuthenticatorTransportTest.java
Labels: enhancement

#145 Make default methods
  webauthn4j-core/src/main/java/com/webauthn4j/authenticator/Authenticator.java
Labels: enhancement

#150 Bugfix: AuthenticatorImpl equals and hashCode methods don't reflect extensions members
  webauthn4j-core/src/main/java/com/webauthn4j/authenticator/AuthenticatorImpl.java
Labels: bug

#154 Pass Authenticator instance to CustomAuthenticationValidator
  webauthn4j-core/src/main/java/com/webauthn4j/validator/AuthenticationObject.java
  webauthn4j-core/src/main/java/com/webauthn4j/validator/WebAuthnAuthenticationContextValidator.java
  webauthn4j-core/src/test/java/com/webauthn4j/validator/AuthenticationObjectTest.java
  webauthn4j-core/src/test/java/com/webauthn4j/validator/CustomAuthenticationValidatorTest.java
Labels: enhancement

#161 Bugfix: AAGUID in packed attestation statement is not properly extracted
  webauthn4j-core/src/main/java/com/webauthn4j/validator/attestation/statement/packed/PackedAttestationStatementValidator.java
  webauthn4j-core/src/test/java/com/webauthn4j/validator/attestation/statement/packed/PackedAttestationStatementValidatorTest.java
  webauthn4j-test/src/main/java/com/webauthn4j/test/TestAttestationUtil.java
Labels: bug

#162 Improve AAGUID string representation
  webauthn4j-core/src/main/java/com/webauthn4j/data/attestation/authenticator/AAGUID.java
Labels: enhancement

#166 Bugfix: KeyStoreFileTrustStoreProvider must return AAGUID.NULL key map
  webauthn4j-core/src/main/java/com/webauthn4j/anchor/KeyStoreFileTrustAnchorsProvider.java
  webauthn4j-core/src/test/java/com/webauthn4j/anchor/CertFileTrustAnchorsProviderTest.java
  webauthn4j-core/src/test/java/com/webauthn4j/anchor/KeyStoreFileTrustAnchorsProviderTest.java
Labels: bug

#171 Bugfix: credentialId is not counted in for equality evaluation
  webauthn4j-core/src/main/java/com/webauthn4j/data/WebAuthnAuthenticationContext.java
Labels: bug

#169 Improve assertion verification conformance
  webauthn4j-core/src/main/java/com/webauthn4j/validator/WebAuthnAuthenticationContextValidator.java
Labels: enhancement

#164 TrustAnchorsProvider using KeyStore object directly
  webauthn4j-core/src/main/java/com/webauthn4j/anchor/KeyStoreTrustAnchorsProvider.java
  webauthn4j-core/src/test/java/com/webauthn4j/anchor/KeyStoreTrustAnchorsProviderTest.java
Labels: enhancement

#170 Add userHandle to WebAuthnAuthenticationContext
  webauthn4j-core/src/main/java/com/webauthn4j/data/WebAuthnAuthenticationContext.java
  webauthn4j-core/src/test/java/com/webauthn4j/WebAuthnAuthenticationContextTest.java
Labels: enhancement

#177 Bump Jackson to 2.10.0
  gradle.properties
  webauthn4j-core/src/main/java/com/webauthn4j/converter/util/CborConverter.java
  webauthn4j-core/src/main/java/com/webauthn4j/converter/util/JsonConverter.java
Labels: dependencies

#179 Bugfix: NullTPMAttestationStatementValidator is not included
  webauthn4j-core/src/main/java/com/webauthn4j/validator/WebAuthnRegistrationContextValidator.java
Labels: bug
